name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Install clj
        uses: DeLaGuardo/setup-clojure@master
        with:
          cli: 1.10.1.693

      - name: Test
        run: clojure -X:test
