name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install clj
        uses: DeLaGuardo/setup-clojure@13.0
        with:
          cli: 1.10.1.693

      - name: Test
        run: clojure -X:test
